version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lootchat
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"

