creation_rules:
  - path_regex: secrets\.yaml$
    encrypted_regex: ^(data|stringData)$
    pgp: >-
      # Add your PGP key fingerprint here
      # Example: FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
