apiVersion: v1
kind: Secret
metadata:
    name: lootchat-secrets
    namespace: lootchat
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7SSen9H6w7KIaFzt5NoGlwvNKDRu,iv:p4FSjhKGBjt5tc1i66WBWozkxiKw4EyvLEc2sG8BjIc=,tag:UqEEb/fv3UhyZaE1769aJw==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:Y0bCXgrrHcc=,iv:lH0/XcEL6Oozur56oMqEXdexvknmMOfLvEdWtErOULM=,tag:fVwV7cIJqmBmE8XcddTmPQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:C+uJ42zOdbAPQxONyIQkV0n08dWBFXjJixoHvCSjO3paKd4BjQpnEm/4Rho=,iv:kOBzGj9MYn7Mv3GZno41s2MmtxSJOAat1yrymQ91UdE=,tag:jmvTberqfLAOCkFgKT9R+Q==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:wK7oYtE51ME=,iv:z75K5cYvvXPOM3VbDlwwyHLU0ovez0DP9XET0J3NJGw=,tag:4Hwca+eaJfVCCyGgoaEYuw==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:9aN7XGDv3Ew=,iv:38LACXBw/Um8TqaDPFusU3Tp31CmnO6yy1YPESjMFDs=,tag:aZxwPd1rHEt6EBC7BKRVBw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:CJ+8SThzouVcJb3Gh40oAlsY2CqtyqdHFUah4kzWpBSkYT2cplRoyHJN8vI=,iv:qFHUvyNCQXx6+E1jo5IRC79cEi5pb7ZemW6ewPT+SNM=,tag:c2mqwxAXYhtw1icbKHe0vA==,type:str]
    #ENC[AES256_GCM,data:/kA5UgGdKl3r/XjNhOrxz3I0PjLR65g=,iv:C7gMIMg9QyhQRObCLAFP+nax+tjPXeVHObXYs275FNI=,tag:hCuaaudYzkyo0HwJbNtTaQ==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:8YPpnp4319zbxjMVJt2lzUdYZlkHM664CIYHr9KqnWiU3d5a2xp/E+UDZuQ=,iv:1IT0TW3fccUZbefAXPk9E37EiCFfJT38vVHK1qbGyKo=,tag:vytkw/NW/JCYfxpzYsocUA==,type:str]
    #ENC[AES256_GCM,data:Zox6AleOuejZds18UdMYpfs=,iv:1XxqYCn0noIGLdokqoGv/eQkJLOuZEjB/kdtCq1OxR4=,tag:Ja6wq65W9XKJtD9Qyg0gDw==,type:comment]
    NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:tRx/5ca5Njd1l/P/ONsiLlXAlFzEx5zj7pfwovDUhcx4BiNC935vDQbcD3c=,iv:XVxhFEyXZmcRsWpVsupzOrvXo4bPchZkVYAxLgosIfk=,tag:VeC7qGzSR63dkw2Px3bwvw==,type:str]
    #ENC[AES256_GCM,data:+k+gtkebA2I7NL16rff2,iv:q1x4jCneU1LNqWRSkt6g7M1CFEIqFop5Jp2gLw8jfXw=,tag:poaL2jWPzLj8fhiEd0xDJw==,type:comment]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:+MmQ6WLYj+h/JBAe,iv:d4BExRcY9DEnKn3zSTfcbpamSJgvuOGluj+jHOA1p20=,tag:yg4GM0LvsJmoJbL9xmA6IA==,type:str]
    #ENC[AES256_GCM,data:PzZ210GhreijSPiN8siUUI8=,iv:hRYge1WEf8P1NEEkHIv0CvBcKyQ+9p/RmtTCF8hdtRY=,tag:CA3Jbbk4IjZ7bAX4PaPe/A==,type:comment]
    MAIL_USERNAME: ENC[AES256_GCM,data:+IYLtjfq2dtHLXbc0JpEXLYvyA==,iv:Hl4bqBrZ69u1CokFs5XsY9sq9DZApo9/2uZrZzmXx0U=,tag:JREITjqeLVdE3ak9MLdz+A==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:wvTj17O4Lta/l4l3ER6gDSPJuw==,iv:F4Omk9atpGJNFhjI2X7L5RFINawF2V3tYp2LWmSzAgc=,tag:IRw88dLUvHWSB1wZPkgumQ==,type:str]
    #ENC[AES256_GCM,data:uXHxAsEOalgOUN/aU23ynAhKXxXc,iv:mFRSs2ZHQZ/dd7lF5qPgsckc3JN3LMG6352pQuWCJ2I=,tag:CIIdUB4P5fuBSlSLMBORZw==,type:comment]
    DOMAIN: ENC[AES256_GCM,data:SkNCYvcknKipxBXHaA==,iv:dJwctzD+VyH8102LOKlI2UFqjJcIKEXGC1CaPqSQ818=,tag:7CGl0xJ5Rpn0IY6Ec3KsdA==,type:str]
    #ENC[AES256_GCM,data:gyDU7su3Q8ll90+ip1LBTNHTJ6/w,iv:dKzuRNWmvXSOiXy42h8jpHMuAjqlNsC0zjuB/f6zmBc=,tag:6Ki+jhLlTgayoF9SdJyngg==,type:comment]
    CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:Cup4122P9TEQtvyTp4wgS0cPB9ZK,iv:7fiVm5b8dcrWGD1aR5jFLd9Skdr+np8dyFK5UVZlw/M=,tag:TjgXvfayNQees+L9gp7AzQ==,type:str]
    #ENC[AES256_GCM,data:DDZK0Qcz4l4x7BGt,iv:SgyoNKNCtYnKYlyXkupmEdlDy0QXATRtk/imbvJg6+E=,tag:ocrsuORDGI7ZAZXxo7hq3w==,type:comment]
    APP_PUBLIC_BASE_URL: ENC[AES256_GCM,data:oDYON/47Z9SxRMzCORW2mObYDAEg,iv:1eY+DFfh9to0D+UCgla4f7pQHM1Cj0BS5emPuJa9wCk=,tag:QlUJNI+kEgvHFzKLJbBNuQ==,type:str]
    NUXT_PUBLIC_API_URL: ENC[AES256_GCM,data:Kih2/pAyU3WeXgWAL8n33vc+p49S,iv:+LZmTZUiyN4Q8PWmnj5NPUJ9/jJ+pZsEz7vCmWh9/nA=,tag:ZMR2kYyxIuxho98/ynUhpw==,type:str]
    #ENC[AES256_GCM,data:z8htWiV1/pAmj05CODE=,iv:QSDAxG/KbSespxpHYy6MX4w6mcT7fknm/A9Ak50woxo=,tag:i+3tZgXAj6MgPvVPTf8zqg==,type:comment]
    NUXT_PUBLIC_TENOR_API_KEY: ENC[AES256_GCM,data:35VEjoaqzmmTtmGkFcq0yGuMmBb+Zw2clAH7p+JDlignr6/F4WNA,iv:a9zAF8r0r+gCdjqglJd5OAfnf7KWfA8fROCZQN8z0lc=,tag:My6z75f7HcxuKY+4iK5Gog==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:foTGHjeUEglHkw==,iv:GQ3vZecuWEd3CuckUMumjLsTMxCZkuRshL1f9Oi7sHg=,tag:eMfkkHy3k+jn3Eifd5YBjw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:UxA2nTXFu3cSBB6/Ow==,iv:eziKoP/+EI1SDs+vG70IPkg1wmsxSUt0CYiy78p7Z38=,tag:bTMjztNs4LWZvM99g8hpeQ==,type:str]
    #ENC[AES256_GCM,data:6jKZDuPDY15PDoUEZ+0LI1iEp+8J,iv:Xki8CkxGEOnydtwKHNFELffyRhWk+TWlseMTbwdIjHU=,tag:KUKrWu78Rl7P7jTdaaJJlQ==,type:comment]
    REDIS_PASSWORD: ENC[AES256_GCM,data:vHxfobK5i5K8jfo0X7rRG8B5HqJax+kffJ6zelHY0p73imQ2s9r2gvaqFp4=,iv:HRbHYSvJFRzJHMXqaCg6Fq+DPtoKaT+LfA0HFFQoT/4=,tag:P2MkxS6BZ+XV1PVksP3SKA==,type:str]
sops:
    lastmodified: "2025-11-27T11:05:03Z"
    mac: ENC[AES256_GCM,data:khHkJm1C6AdFRkce6E2NrxdS+2SMom1K7rGk+eGGnr9ASCkDLY2DvmSKCgra3b30c4JGHmsEKMSirmBxp+RrJdDCvysaM9PUnEYcQyDxde0EshvuQ1ZPKPLpNv6GLOaO7QOt92iwNUenxpJaDNh7n7RN6i2sXZdp1n57FfArBaE=,iv:ZpgN/9u4QUmW6nlM7OjPijNCo1+0AXdGveOsW/Rdg0U=,tag:LPbJpJczWqFW2Slx0ApADg==,type:str]
    pgp:
        - created_at: "2025-11-27T11:05:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9hFgxbSVD9qAQ/9FTJ2DKkBAI8RwISIrGubJ7oYq4iOouSvvCLhPMNyrGIQ
            M22eDpqeKBRmCTmQwlgMMJWgsz4vBO1x+TjuoNKjPYvcsyaHe5v5R7GmqH4R8en1
            YmJR4uKogwgFbjPbDiaYGeXb1nzoelIIPQSB58NAnhGK9X1L68gnlkG/wfS3brAw
            9uKaMkfsyCx3OCmleIknYnqyjbmff1n5D/sMUyc9GcsfECj/wMgQRMcBlStuhjIq
            jHPg+I0kyJjz3lq2Gg+wg74BzPBgge0gJMAPR0UC3kAZnQSSKBikb/NuhSgu/DLT
            LqWJhx90EJWIAJ14RvFSnCPeWNTSFDFc3BORz5vo8EGX5Or5inHjQXFxEA1NlcoJ
            Kh4G3PolDBepZ+INTqAgMN8uV34S/xQF4zg/xuB4qktBOUxjYuYJbnx8DuW0Em08
            8K2B1roPCR/aJUAvE8VoWCP5CJEfQWRDXRSVGSnQN36X8UAygoTCOR3vAZnZVP1b
            rv86O8vEg7qB/RCDaEmKlX6EQpwy91/QB5tyvND83zdtBXitMnnWWZjvMXKxqYvH
            RxqD8sDgfZFKU650TxG9YSYFFWAuTOhmEMhUZxjmflP340PpDHrrOMeZyXHQzttX
            08kxh50Pp9ztJ7Mb95d1UmZ9HmHmvymgAL79lpECpfijIoACoesZat6ljbrEbeXU
            aAEJAhB+xAq5oeDT59RDyt9I3DgoRaxkEesKN+Bi+wW2tVlHj3neeGXgYQneEsHr
            eHP9NaNTOst6IZTEFB4jNt7duSA4mYCC3+zPErp9KQY24HfA/sH92HxbWBc59uZL
            imyUSEoVR0St
            =AoiL
            -----END PGP MESSAGE-----
          fp: 257FE55DA640258047E315BDA1A93F69AFEE8BD8
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
