apiVersion: v1
kind: Secret
metadata:
    name: lootchat-secrets
    namespace: lootchat
type: Opaque
stringData:
    #ENC[AES256_GCM,data:PQqGNsvqCUzUlg8CkWBSfZxv3MkQ,iv:/HFqkaQzRC/XMONp699dVdNqLWWD3h/bxzZRzpffwio=,tag:ezjmkByOoVnPJIkMEZSjKw==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:bhbZ61PXKTo=,iv:qnpmnytuRfnw1ctYg5aBGuM/KiDjw2WK6PZ7ene7aRU=,tag:ekv/KL6RHd2PoiRc4Tib/A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:B0XiKTYFvwll9vjPz2XknEqMMLHZ1cJmS5Fth3D4+rLXUDAUXgH0HbHfCw8=,iv:peJOIvYanP3Tn7qVpIzOK+UqgUFS0v2fCLWHC7RlfAY=,tag:0V94qP9dnIjxAjZu02G5KQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:4Lrrn+UpaOY=,iv:BTU8U6NnSukCtriua16PhrM+Pq5SLAzr0wCxrUhKC4Q=,tag:6r9BwerSnmVKqzUMFobpqQ==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:SRXhb+uBHwc=,iv:hs4lmaYaAR7Lw2NfQF2Bzx9wFrCP4cXgT2pehHgjIak=,tag:jqawgxPtBKkLclagxWIcJg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:3zkNQj5qj/G+qVPveJgXdciJU7ddTxGh4ynj9oPghnRwCzknRgC+PqfdnN0=,iv:vwkmwOD9F4b1KVo4vpJMQo2WxT1IFJSF0ziyUILkyPU=,tag:yzHzOeki9tRTIEykPFbOig==,type:str]
    #ENC[AES256_GCM,data:ALcEtC3X2hHADWA6nGnpcv5l6Be61mI=,iv:Vfa/Ban26TQxVV1jBKmBZtTIVTOHrVs2sdXq2MCbJt8=,tag:hKOfJViPDbJOzChujGXqlQ==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:EdYYIbJVpLaqWpi3REzNOGtZDEmU/k0BfRXRsJI0RyEMhKni54VDvA1ZPfo=,iv:WwXsSZTyKs6d59pVMv5AXk1EnBjHl6O50W+u6x2x95g=,tag:79jgs4PeWiifIZ3IRuvMiw==,type:str]
    #ENC[AES256_GCM,data:vdcnnMvHPJT470Bw5g9r4OE=,iv:q7Uf3QhVec9U2D1ElIOrhz6RXP7gMHUojZgeFkVpno4=,tag:evHkuUfMmfY4mgY1+QhgEw==,type:comment]
    NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:xC9yZzrlQSUDlWG3Y/3VsXFCkXuunsF7mFoln7CEytr1Na0rjbCAQV41ySY=,iv:XSLdixQKlgDmFv1JuRMrprNYfJ5ZrrlbMcyJqsyg/2U=,tag:p6EHJq4iL+YIVitzblXSpw==,type:str]
    #ENC[AES256_GCM,data:zg3mtC1/blIoZRAkwpyy,iv:uEXDhBNJB5+fdpQ/0ea8XEosa7xkIWRCpGJwiHt1Xks=,tag:qVQJGauTF2UyXdYR+Mph8g==,type:comment]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:YgwyO49mGXDvR+Iy,iv:EIX83yYh49k+SOrqQtfEG401TXbdNuryciJac3uW6OY=,tag:sPEhqSDqV2JuldqrS3KK7Q==,type:str]
    #ENC[AES256_GCM,data:VYrKpUdb8G7YZ8Dfe8W45Oc=,iv:bKOwFS30jQtAe+3+6tZCkGXTh96cPQ3NbpRYepxROgI=,tag:5bctSIB/pBnL4pEXNsNQmA==,type:comment]
    MAIL_USERNAME: ENC[AES256_GCM,data:VcMDs/Pw86E7YDdfmUQNUshkzw==,iv:M/JEqZhVypapHBwAKixCzgU4eVWaH1kiE4JcTjXT3zU=,tag:ot7V5DiCtd9ZnC00wNI1ZQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:/vsRfhYB6yVQVkDeML6cejfxLg==,iv:clGErOi94fY4qvx5nQJRdd+W74xuBV3odpR4YlQn6qA=,tag:W4k4vwlNR/absNCwyFcQ3Q==,type:str]
    #ENC[AES256_GCM,data:fwJ1ZIb7/ngK8swtI7tCnE5PyxtU,iv:YRl+p/n/Z96YuzxyZe27lX/OmUgWtjX/lYYTzplR6y8=,tag:vwJcefEXbrVGx0kXUCZmIg==,type:comment]
    DOMAIN: ENC[AES256_GCM,data:3Fm6dPqADurGFrI90w==,iv:0MD42QPu9fvOl3ukTEUEBoDRN/QmlzkiUIoR7qXh6mE=,tag:MEwecqVRGV0FyW3MATRcaw==,type:str]
    #ENC[AES256_GCM,data:yiHthfYTWoZxLs4LgMvAz0Gl+m5P,iv:4W5P849AxDnRCS7WUTm5M/XhfdtX130Vu76R4SsI4oQ=,tag:Uro3Tj9faAM6eSVD/+xK5A==,type:comment]
    CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:vNmx/J1aOj12dkp8awMRMC7ISaLp,iv:8YsVuHKSNsz2hQHEZG2ooJantsiCs/D1A1plBvh83mc=,tag:FVbmtFR24P2sFW1RfjkoVw==,type:str]
    #ENC[AES256_GCM,data:RJQOill8H6r+yTwe,iv:EHW5K9veEF+gxbcZXHtjdfvXy84QeiaI2ZKwpeqJeus=,tag:7R8Vvf1VFu37wcREep9B9g==,type:comment]
    APP_PUBLIC_BASE_URL: ENC[AES256_GCM,data:g8HyCj13wSnh1/AuepXiDHQDbCZV,iv:BnBqcwcHYRIBnd0fXXRE1c8tj8LfcwPr7W9kUc75Z2A=,tag:vltJ2sc3AJ8PQ0kcS1lwIg==,type:str]
    NUXT_PUBLIC_API_URL: ENC[AES256_GCM,data:R/DnRa/xvKq10fQBiNaLfCX9CxJR,iv:wzmtHSOuvL+volECdtQd/i0eanDvDrqprlMp+9NJgFo=,tag:zVs8MLKV0Ptxp6oxCIVtbA==,type:str]
    #ENC[AES256_GCM,data:GPPRkiQc67qS7QfSMkE=,iv:KroEXLg0dDdkqm/D+7ssZ4cIwWqBus/RJzJ9n7QABs0=,tag:OAYCul8qEQj5wdnrVnBsyA==,type:comment]
    NUXT_PUBLIC_TENOR_API_KEY: ENC[AES256_GCM,data:3wcy53+VmCXBgswbFnwmEEC+vEzB6AgP8EhFKHUIP1bjYeK4T6Zd,iv:SM4UmlftQ9129jl2MlgAGJqglMHP9n/M3dROiZbDP2E=,tag:5ORzUM1gcSMbWVcDyYdUjA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:nGxFvPNfEzy46w==,iv:QnauCrqlYFhYbYaNiUf+8Qe6c6AZPcPSvnAUMHIBwpc=,tag:CPmaM5s3yjvX+LEPynRMbw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:eJjJFN0/RjQRhAGq6Q==,iv:L87IcpD7+6B9JfdikrbQ/TSbD6+qvCyehFOA5lOrDWg=,tag:FCjsje55mwlByA2V5o2naQ==,type:str]
    #ENC[AES256_GCM,data:k4XX7oPI7xOtESnKhBSKa5/bmaBJ,iv:KguFYawP6tOGWjqRtbmfi+LGan9pGVKJF5wt5KyBH7U=,tag:VQsvQcrCyvVYtfUvVs4xpw==,type:comment]
    REDIS_PASSWORD: ENC[AES256_GCM,data:0HuRKS9i3p378JyH4PY5xibFFwHISHQb73yi8DmqbMwQNS3Is33rRl325oE=,iv:oWBmvDBqpUre/9xt1jGuvvo+h48wqA2x+u+VDVBifHE=,tag:FL5bt+ZHvwaCoVF+EZ6QXQ==,type:str]
    #ENC[AES256_GCM,data:+sf/FVsYaeNb+g9QAL/ZSQ3s6TfExfh4+00G0HrEKg==,iv:9at07jCYPqCX4gFs055YMMBcG1wakcrH5IQcNzNTdGA=,tag:jS62ZetwM/ZcP+iFxOtnXA==,type:comment]
    TURN_USERNAME: ENC[AES256_GCM,data:YPwWiHIv0gXlaj9Xe4VZEg==,iv:Qh7zGyXNDZOcYAwyaYB+sNeGlMuaxv82nG41JUHJPuo=,tag:0dqgnts8PVGA5bNccs4eXw==,type:str]
    TURN_PASSWORD: ENC[AES256_GCM,data:yKiefxk17OnxWbm4uQKnsKw54sh96gcmb0iE4A7HZKg=,iv:GSYIIQXR5PrJdZQH9julk1xhL3LmzKfT+ZIN/Axl5ro=,tag:0Xk4piJcSv2T8IAPxW2IBw==,type:str]
    TURN_STATIC_AUTH_SECRET: ENC[AES256_GCM,data:JviPX4xNFq9xJVMLa5oIoFAy3Emkmt5IhdPW1tWagjNoVjcGlAFaLA==,iv:yVEEk/7eurqP1kJKkkUrynyPnoQzpJVoP0PUQK93scI=,tag:uBw3GFweoWKwysRDGhfW/Q==,type:str]
sops:
    lastmodified: "2025-11-30T00:43:30Z"
    mac: ENC[AES256_GCM,data:VgEESZca8fMFpH/R09WUOUsd4LmuxSyZuwMRPDImSvu+nk7D5RGcjdQDb9TZYcbZWGpXmef+JDvSZqMIVThMP7Ac+NBWPFfrS8ojU1P9WZ3adwY3vctaus0SNiSrCcfCZJYaqFsEO7jh2CX3zYIh2X0+crtDVPwv95JP8ZtmIY8=,iv:RMyVjJwzFDx5Kh2IM4Pe0VTzcxIIRPvZtXRj/rrrick=,tag:vqDPkPsaHpA/RtbBp7X4gQ==,type:str]
    pgp:
        - created_at: "2025-11-30T00:43:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9hFgxbSVD9qAQ//UtgP6r1NguvEY3z9fwYbtIUnM0nd3ShWGSSVa2AeUwuv
            PBLyWz9lZSaNyTnp0dlPwN563aOTjdxV2jaH/g36ZFC9OnuPULzWs+I+MPPxBQse
            S1uLCAJB3W4tpMv0OSe+zJuIPOEBMwP7PgmtM06Jw+uBlefbmQHJAZKoFQjFNM1A
            HrJOLkPK9ZutqlZXkpAoUTaH9Mv0ZorhABOcioXmxj0/+gpA7tLDpbHaqqbDTuDz
            UubBRKR8Lx8BqiY9HsW0AhiKMrh23jCeYNdyKa5x38VRt35yk/FVlwm5M4yvWjA8
            LK0IfJ7w4g89LAehLSK7/1QWvG3pEC7V+KFVe8g1g+pdRmF1i+U6MnSbdXmdU0Hd
            AvtnS0copGFyExOaOzJugDh1xXmSx9jSyNY2hTsU7qwMKIUxG3A8Q0wXEJpY5w6J
            nmcTurKcDMxL4jjrwQ2UX3TZjGJi9V9pX/TllsO1aD4aaf05gh6IKDm1EZHJUPUt
            rr0tWSLZ2d7S9BKhw17AL1MpRki7QM2tqrMXAnYkCde3FoRL/HEVoNUn9uU3xUBz
            tM83BST0bmu1yMqvNpKhwFfu5ZWt/6x/a+XDlDM1o+pi9WiMBoJ/9dBxnk/zybo4
            ON4lkh2F0HF9zstp9xRR0k3aKF6zL1/1HUbbmV4NwyGLPrBDuFGRhY9usOScnFbU
            ZgEJAhAIAs36rToZAdtKKowLDegLYr4Vzoa61JgW73N2eXB0KgG2VT6K7OmsYbwP
            v6DkFaHit8ZjHUhm2w0ciijJDAUK/VBI8tFYYaVMTzI+y3MUJkGlD0hjlMeEIKq9
            gkKWgYUzHA==
            =KVzk
            -----END PGP MESSAGE-----
          fp: 257FE55DA640258047E315BDA1A93F69AFEE8BD8
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
