apiVersion: v1
kind: Secret
metadata:
    name: lootchat-secrets
    namespace: lootchat
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/7niaulTLuWg+fox/DXznNoXxbXq,iv:W+1MFcCk/B32Q44tXviEI/CpJaX09MQHG5sIGbOt+us=,tag:g7z0WZsiyNxpMZPQxKvYHA==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:0un779bp6qU=,iv:VDRAiVdInonTb35y0h/P+oM93sYtewb5cDc/vksNVwE=,tag:+iX9NrX5kzE8bERfjONyNQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3IkvHUMakdhgJGCDRQ4WoIaSMagtxKAfmfzY2J7YJAT26WeeOcZKeh1+GxI=,iv:U7jtO0qooAAuZOvuv7MFPzSDfybXGOEkVTNym2iCKXk=,tag:3tuBFWtxFZrVNN6GIHgiGg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Wh4jdkGDKRU=,iv:Sv+sEmnICjkiRhAtmnsRk65A69dOH/KpC1wGla0RngI=,tag:kIogakWdAzbr6ep04ggulA==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:8qOgD9iqExI=,iv:Elk8UWLafexWfczQHABdDpAZXPym+13uE9SHMZBFRnk=,tag:sf0zhe2xDMM4erUoGoVlvw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:xA4qrnlBjF0Ix+GKNjhtbzuytJzfDRuFM7Iryz/ZV9RA0enzAQtt5F+zLvE=,iv:F6+SOLfFMOHpDdPg8JfiDTVGX4ofbTjtljL0v1PoOvU=,tag:gdQ04ktZbOwlq5oxL3coJw==,type:str]
    #ENC[AES256_GCM,data:FBfy3elc/bo2D2g=,iv:vH3ZXyJ7oTD1o1vOYYqnfl7s5QTFrcUcNPzUAwkwW6o=,tag:3tbg3ptVMOmhvU3usM6LPA==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:pM7Ba5yGxW9Octs36Z+2ZEJs/Jc07QHvEfZBgKRKC2rckynf4g7zAe4BP4o=,iv:0/vlT75MMmK9+CfgJ5S0GEmRJ4cmvfjFEdvF+08mpys=,tag:ffzHYQUrDDrpN1qvw68Jpg==,type:str]
    #ENC[AES256_GCM,data:UCM96AQozTCjjVviMU9SQTY=,iv:aW6Ttwlcx8H1VRRHDDxwFXKNsbhr2NSiXGUeIY6mjOM=,tag:ej4rDN72jwm0XW/XWRQM9g==,type:comment]
    NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:dzDr0s5vruWrxg6McwUoxr2aEdhMcKV/uWSZYqMKRjDPncbfmhgefoBjYlU=,iv:+FLZ3ZVrqpJOlmJYJzDmFFnMN+skBLIi3E/dYDxiX1A=,tag:yC63f8baSpvFTOx2IybozQ==,type:str]
    #ENC[AES256_GCM,data:ZjUmQbE/18y3ONmkwTf9,iv:Xj6TtH3Pnw4SEPxizkYGNNlNKMr7hy3tZ+xya2xadm4=,tag:PCNKUWkkEDoxXBr7XXLZKw==,type:comment]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:4uU+uwalFs47Qz0l,iv:R6ODxNhtoN7Ul0n6QN0d50k04T0rh2TNuAtA7Rrf7uo=,tag:ifGZ1JhPKICov12Vff7XdQ==,type:str]
    #ENC[AES256_GCM,data:QaBQYekHgOKog1D6X6VDL+U=,iv:D4R1Dii976lH6iHvfplIjTFoqeDulNs0dxStG3KWJrI=,tag:E1+ZeqY/nlJwErOlGTtTsg==,type:comment]
    MAIL_USERNAME: ENC[AES256_GCM,data:/+/AbteD9p2toEyiKYgYs+PMAQ==,iv:EnHu/uNn9KNW322PPertjxMybTzV1/AG1Slq2h/dJPI=,tag:UhfQgHRX5j6mRnCXOgdAYg==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:HaAD9f3CR4J8qdQHfIvseMYe5A==,iv:B9/4AwnR10cMtv46I0OZJGyM52QGCZJMYLmvTMwtrmU=,tag:z5VVV42A4Pqrc9gK/dwlaA==,type:str]
    #ENC[AES256_GCM,data:4KoPUU2SdjX7K2TykzeHytenBVMC,iv:V9wX+3sASwgpHhvjt8EB0wZVYEbUFevXalArQ7/aFPw=,tag:0fx275o2RrRhXAFSpfp+uw==,type:comment]
    DOMAIN: ENC[AES256_GCM,data:0WVKK5dBonfGql3UlQ==,iv:zfGDeXlNvevGFwciweABJPBuR867kz7dGBEF/aDsJ/A=,tag:VpkJ6/uVUkdL5FTxVnvq9w==,type:str]
    #ENC[AES256_GCM,data:3AJnFYpJG78VMctOorWmiiCqHgBT,iv:mK4SuL189nq9QDfuWdmx4zRp5/vMKv/Y5m/LzRUgFhM=,tag:EAy5hkdn+3PPzzJdNownZQ==,type:comment]
    CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:8jSNj1LbctM5ygK3mDjA/P9ZNBMu,iv:IRPEkEQwuJmjpJutLy7MUH0xZOLhJsxchktYE8KlYxc=,tag:s3NtAPgP6dZu7PESiuUptg==,type:str]
    #ENC[AES256_GCM,data:xoWaIm7CGXI0ibPS,iv:rlZ2BuTpHDz/fhr358rX2MoMaOQfwahEUC8RENwNegs=,tag:/6oUdV/nzJSYc/BPxYUhGw==,type:comment]
    APP_PUBLIC_BASE_URL: ENC[AES256_GCM,data:DCKBrsfsq0CzeS9xKx2EXME8UT0u,iv:ifWU6lbnGN/c6rkq4/+np0JPtGY28oZqtygRkRkDimY=,tag:pxAMNZJzxE8cp50E5peHSA==,type:str]
    NUXT_PUBLIC_API_URL: ENC[AES256_GCM,data:r9KaO7m3e6V9yEzHMYuM2fxwVm6u,iv:aCMzppie/C+GuCDmH5O4ant7PLEDSEs87rlSEdCj5bc=,tag:WasTZyqQ56BDoPVu4xDsYA==,type:str]
    #ENC[AES256_GCM,data:s6PHtVG/Tlc4v8Pei4w=,iv:gbiKNLKIuSAa99yG1HNAmsVNCnxd+XyORsUeBFxPFoU=,tag:BfDXiIzLDgNl4jUbdZn5bg==,type:comment]
    NUXT_PUBLIC_TENOR_API_KEY: ENC[AES256_GCM,data:K2eIZYmQFazlNZC0WUAzy7/V+rBXoUglLPXQQXzxZw/vfre+Tu9P,iv:uwrDt+iqNY1pOmdki+8zvMZhoCuKwOfNMTlOxaLs8ZY=,tag:nRNNCjF+nXHTyM1LNpWTXA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:t7RhjZaEvSBLRw==,iv:5MQfepg+s+zOElXKjqFrUlotWS3Q+eRDPVhaY+TdsUA=,tag:DtlrLJRzdb/Ek342WSJimA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:W9oseAMJvQpzK+ns3g==,iv:6VOtHQCL682heigwOqhZV6D40/RHqP3fDXiOSi8BZNU=,tag:WoC6CNCAbBwFtnaWgfxqZQ==,type:str]
    #ENC[AES256_GCM,data:I5AphYAx3PqnkfzfV2EVD3bNNoFw,iv:h6uakEnmjun5t1lZ9h+egZpOGS/CBZcUCl39lCtbaFc=,tag:YDE+JrOkGYAuedR42VxAGA==,type:comment]
    REDIS_PASSWORD: ENC[AES256_GCM,data:nPM2Hna504f1GTytJTgwFSSBQf0j0Y5x2n8+UBF1rahazA4ZmkE6iz+Z7f0=,iv:4HLxYbfKUzlAcahQOtCew9y3qOcqhjO1Y9+8VRV5DMQ=,tag:NoHq5DeCmA2EsLdyS83noA==,type:str]
    #ENC[AES256_GCM,data:HfNBeNOUTC/CjVgIU29rjAUvPkTr8oUo,iv:XcDHdpR3K+zakIP90wWmt6SvSbfujHQI4Z4awYRh7ZM=,tag:GtHJ5mDIXcW+fBR5iqDfsA==,type:comment]
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:VJs5PrJ7BpCrRQzU,iv:qB38OrwSlNochUaiSkz/T7qKL/QIQTM7RO6NwTRvu8Q=,tag:L19uJiaEUv8IM2e+7L6tFg==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:CUxDw6KWdNfeESagBpIE77SG9Ucru3qwCSKIqsU6iP0=,iv:FBl3X0t7s6CkNr7gsgheT5T2texY8N0Z8t1CD/vJfRU=,tag:2crHKgF99x9iGAD3ss1/FQ==,type:str]
    #ENC[AES256_GCM,data:DjS+wJQKKNxcfY9hvehAXQ4yy00WD++I685AQ6ZbHoofMPKUWfB73xGF8hZKVcyr6s7v0xAihe1De3oW,iv:7O9dnJz3b2G0xNO210f/BjRo5Ow85O9b4m1SUM97gQM=,tag:VE1aZAt7EheVJUxq7CJeng==,type:comment]
    LIVEKIT_KEYS: ENC[AES256_GCM,data:Bp1LnA/i3ydgfGvnOz0cbEHp5Gv4CW/91qfgX7hY2X3YfWny0g/3y5WcWxmqbg==,iv:83Nkr9XOl2bxJFpTRGPJn4pdjKxHqF6zTP8ongBlF1E=,tag:Xo6S8uGnos2JLBe48dOA0g==,type:str]
sops:
    lastmodified: "2025-11-30T14:35:17Z"
    mac: ENC[AES256_GCM,data:d+/iAXRbwUzs1UnCQmlBbO5+u/2V9bZ4dHVa+K3DfMsp5iiHKtf22L9oFRzUA6+Qvv79sxld/YSYMS1OGOD3Hki+ibuf7ut/ydZFAq0HwdkDfU4nVg3h20GSbPZXX8itd8J32LbQZ/PkMsBpYGIkY4P0XgqvjAv0ZfwqlIU8lLQ=,iv:XyZ6HN8FU4F95k4JPN94aZlS6SZI73FLH410FQsltuU=,tag:x1joNfPjD+xxwgcza7OD3Q==,type:str]
    pgp:
        - created_at: "2025-11-30T14:35:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9hFgxbSVD9qARAAiKGnonf7/4dN/oFZuSfkrMiAvgVM95XoNa0rB/cFu3si
            dZfBtpmVSMvhyDWwruyKJNkBVOllOLqzx4B6vK70+kH1nkjdbQpkHbNNwcASF1y7
            HPlCxGt4IgEgy/PIA/J0YOLjDA+nF0sHEZeT5xYb431iTEx3/N+YWVCUIID4USYk
            PNE+s5kmjUttzO5A9ZC2ghIvGIs3fYnYmvxN4bBglhiZlF18H3ffNyKA6SZyCsHT
            yW9QPoh3AW8QQuomc8vPppGSlXkCH4Vk+DrMbyuPRpRewr3KboBo4HvkPHzc0ELq
            eQ65IM2d+bxCEJK70Gnt/XNaqqMxsQsr6lm7JZatOmZlORPekjnxN/YUmNadaucm
            8w5Ziq/huKwIUaciexM8EmQjoNlt1g5wagNU432OTKWI03uDqIXKZQiB/nbBJNZc
            TVVMT6nHLU6iV3hbsoWv4v+qQ/3bSevwRdwFEzCEG1xZV5vtPfE5OD2dVaP854Yi
            gHpx1secfi/4pAY+glOrDauw9Emn5x5KQIEx0wXjjAyTlFtEy3B5/XLOdCnm8Yoy
            gu5uOWLjO1kp9CEG6DN0wY+x/qdq0HLg/661blcjT0r5M3bn9P5SI9zwC2DERZmR
            C5uJ171igPfd+GJDZazjpdezNFnTToI8NqWcfCywn+oV0pymTk+RLUppbvqMBY7U
            ZgEJAhBJDCE1H1gWbx4t7umf6ihgqkJA+EB4P7iDKyWw4Y/SpZj4Hz3VWMmzxQGY
            P0zCIavL4VTvgr+TS3+vvuq8g4yRr8NM52OAEbutzWwpDTu80Fvy4y46INBH6yGh
            mHSKUsgp4Q==
            =ldGh
            -----END PGP MESSAGE-----
          fp: 257FE55DA640258047E315BDA1A93F69AFEE8BD8
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
