---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lootchat-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: lootchat
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: lootchat-backend
      namespace: lootchat
    - apiVersion: apps/v1
      kind: Deployment
      name: lootchat-frontend
      namespace: lootchat
  timeout: 5m
