apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: lootchat
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-grafana
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-prometheus
      namespace: monitoring
  timeout: 5m
