apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wireguard
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/wireguard
  prune: true
  sourceRef:
    kind: GitRepository
    name: lootchat
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: wireguard
      namespace: wireguard
