apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: wireguard
data:
  wg0.conf: |
    [Interface]
    Address = 10.8.0.1/24
    ListenPort = 51820
    PrivateKey = SERVER_PRIVATE_KEY_PLACEHOLDER
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    
    # Client peer configurations will be added here
    # Example peer:
    # [Peer]
    # PublicKey = CLIENT_PUBLIC_KEY
    # AllowedIPs = 10.8.0.2/32
